### ISSUE TITLE
The Grand 2.0 Todo List

### ISSUE THREAD

**Issue by alexmoore** [basho-labs/riak-dotnet-client#200]
### Bucket Types
Continuation of issue #175 
- [X] Add buckets to `RiakObjectId`
- [x] Add Integration Tests for Bucket Types

### Data Types
Continuation of issue #166 
**Data Types**
- [x] Counter
- [x] Set
- [x] Maps
- [x] Integration Tests

**Bucket Types**
- [*] ~~Assign a CRDT to a bucket/bucket type~~ Command line only
- [x] Integration Tests

### Security
Nothing done, all todo.
See https://github.com/basho/riak-java-client/commit/00e7748e202eb95ac108d3ccf7ad92f53688c909 for Java details.
- [x] :allthethings:

### Yokozuna Support
Recommending users use the [Solr.Net library](https://github.com/mausch/SolrNet) for real usage.  
:bulb: Could (in the future) have a CorrugatedIron.Search package that's external that pulls in that library, and autoconfigures connections based on your config file settings.

- [x] Add Yokozuna administrative functions / interface.
- [x] Simple Search (pass simple query via PB)

### MapReduce
 - [x] Fix parameters to include namespaces/bucket types

### Strong Consistency
- [x] Add property to bucket to query if it's a strongly consistent bucket or not.

### Cleanup / Tech Debt
- [x] Mark any `(bucket, key)` interfaces in the system as `[Obsolete]`, offer replacement with `(RiakObjectId)` instead. [RiakObjectId](https://github.com/basho-labs/CorrugatedIron/blob/develop/CorrugatedIron/Models/RiakObjectId.cs)
- [x] Obsolete any HTTP interfaces / support. (Hard delete in 2.0, or warn and delete in 2.1?)
- [*] ~~Fix Async.~~ **Moved to #248 **
- [*] ~~Fix any unit/integration tests that are deferred or non-deterministic~~ **Moved to #248 **
- [x] Streaming 2i Queries - Test / Implement?

**Comment by alexmoore** [comment]
All major items done. See #249 for remaining small tasks, and #248 for post-2.0 cleanup.
